import React, {useEffect, useState} from 'react';
import {SafeAreaView, View, StatusBar, ActivityIndicator, Platform} from 'react-native';
import SplashScreen from './Screens/Splash/SplashScreen';
import {NavigationContainer} from '@react-navigation/native';
import {Provider} from 'react-redux';
import {Root, Toast} from './Components/NativeBase';
import AsyncStorage from '@react-native-async-storage/async-storage';
import GetLocation from 'react-native-get-location';

import {GetAuth, GetUserId} from './Redux/UserDetails';
import store from './Redux/Store';
import MainStack from './Navigation/MainStack';
import PushNotificationIOS from '@react-native-community/push-notification-ios';
import messaging from '@react-native-firebase/messaging'
import PushNotification from 'react-native-push-notification';
const App = props => {
  const [loading, setLoading] = useState(true);
  const [userLoading, setUserLoading] = useState(false);
  const isScreenshotRun = !!props.isScreenshotRun;

  useEffect(() => {
    if(Platform.OS=='ios' && !isScreenshotRun){
      PushNotificationIOS.requestPermissions();
    }

    if (!isScreenshotRun) {
      getLocationdata();
    }
    hideSplash();
  }, []);

  const hideSplash = () => {
    getAuth();
    setTimeout(() => {
      setLoading(false);
    }, 2000);
  };
  useEffect(() => {
    PushNotification.createChannel(
      {
        channelId: "123", // (required)
        channelName: "My channel", // (required)
        channelDescription: "A channel to categorise your notifications", // (optional) default: undefined.
        soundName: "customSound.wav", // (optional) See `soundName` parameter of `localNotification` function
        importance: 4, // (optional) default: 4. Int value of the Android notification importance
        vibrate: true, // (optional) default: true. Creates the default vibration patten if true.
      },
      (created) => console.log(`createChannel returned '${created}'`) // (optional) callback returns whether the channel was created, false means it already existed.
    );
    const unsubscribe = messaging().onMessage(async remoteMessage => {
      console.log(remoteMessage, 'remote message')
      if (Platform.OS == 'android') {
      PushNotification.localNotification({
        /* Android Only Properties */
        channelId: "123", // (required) channelId, if the channel doesn't exist, notification will not trigger.
        id: 0, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
        title: remoteMessage.title, // (optional)
        message: remoteMessage.notification.body, // (required)
        foreground: true,
        userInfo: { data: remoteMessage.data },
        playSound:true
      });
    }
      if (Platform.OS == "ios") {
        let details = {
          id: 'notificationWithSound',
          title: remoteMessage.title,
          subtitle: '',
          body: remoteMessage.notification.body,
          badge: 0,
          userInfo:{data:remoteMessage.data},
          isSilent:false
        }
        PushNotificationIOS.addNotificationRequest(details);
      }
      // Alert.alert('A new FCM message arrived!', JSON.stringify(remoteMessage));
    });
    return unsubscribe;
  }, []);

  const getLocationdata = async () => {
    GetLocation.getCurrentPosition({
      enableHighAccuracy: true,
      timeout: 15000,
    })
      .then(location => {
        console.log(location);
      })
      .catch(error => {
        const {code, message} = error;
        console.warn(code, message);
      });
  };

  const getAuth = async () => {
    try {
      setUserLoading(true);
      const value = await AsyncStorage.getItem('user');

      if (value != null) {
        const result = JSON.parse(value);
        store.dispatch(GetAuth(true));
        store.dispatch(GetUserId(result.id));
        setUserLoading(false);
      } else {
        store.dispatch(GetAuth(false));
        setUserLoading(false);
      }
    } catch (e) {
      setUserLoading(false);
      Toast.show('Something went wrong please try after sometime');
    }
  };

  if (loading) {
    return <SplashScreen />;
  }

  if (userLoading) {
    return (
      <View
        style={{
          backgroundColor: 'white',
          flex: 1,
          justifyContent: 'center',
          alignItems: 'center',
        }}>
        <ActivityIndicator size="large" color="#223F9A" />
      </View>
    );
  }

  return (
    <Root>
      <Provider store={store}>
        <NavigationContainer>
          <MainStack />
        </NavigationContainer>
      </Provider>
    </Root>
  );
};

export default App;
