require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
permissions_path = '../node_modules/react-native-permissions/ios'
platform :ios, '10.0'

target 'fti_coach' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  # Only the permission handlers actually used by the JS code are compiled in.
  # LOCATION_WHEN_IN_USE is requested in Components/TodaysOrder.js; camera and photo
  # library prompts are raised natively by react-native-customized-image-picker,
  # and notification permission by @react-native-community/push-notification-ios.
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'RNFileViewer', :path => '../node_modules/react-native-file-viewer'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'ReactNativeGetLocation', :path => '../node_modules/react-native-get-location'

  target 'fti_coachTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  # post_install do |installer|
  #   react_native_post_install(installer)
  # end
end